version: "3.9"

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - db
  db:
    container_name: basic-api-docker-db
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
        - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
